In [16]:
import numpy as np     
from sklearn.datasets import load_iris
from sklearn import preprocessing

def main():
    X, y = load_iris(return_X_y=True)

    selected_columns = X[:, 0:2]
    # Write your code here. Do not change any other parts of the code
    scaler = preprocessing.StandardScaler().fit(selected_columns)
    scaled_columns = scaler.transform(selected_columns)
    #uncomment the two lines after assigning the values to "scaled_X" in order to complete this mission
    print(np.mean(scaled_columns))
    return scaled_columns

main()

-1.6460906711775654e-15


array([[-0.90068117,  1.01900435],
       [-1.14301691, -0.13197948],
       [-1.38535265,  0.32841405],
       [-1.50652052,  0.09821729],
       [-1.02184904,  1.24920112],
       [-0.53717756,  1.93979142],
       [-1.50652052,  0.78880759],
       [-1.02184904,  0.78880759],
       [-1.74885626, -0.36217625],
       [-1.14301691,  0.09821729],
       [-0.53717756,  1.47939788],
       [-1.26418478,  0.78880759],
       [-1.26418478, -0.13197948],
       [-1.87002413, -0.13197948],
       [-0.05250608,  2.16998818],
       [-0.17367395,  3.09077525],
       [-0.53717756,  1.93979142],
       [-0.90068117,  1.01900435],
       [-0.17367395,  1.70959465],
       [-0.90068117,  1.70959465],
       [-0.53717756,  0.78880759],
       [-0.90068117,  1.47939788],
       [-1.50652052,  1.24920112],
       [-0.90068117,  0.55861082],
       [-1.26418478,  0.78880759],
       [-1.02184904, -0.13197948],
       [-1.02184904,  0.78880759],
       [-0.7795133 ,  1.01900435],
       [-0.7795133 ,

In [17]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

def main():

    dataset = pd.read_csv('mushrooms.csv')

    y = dataset.iloc[:, 0].values
    selected_X = dataset.iloc[:, 3:5].values
    le = LabelEncoder()
    encoded_y = le.fit_transform(y)

    ohe = OneHotEncoder()
    ohe.fit(selected_X)
    encoded_X = ohe.transform(selected_X).toarray()
    # Write your code here. Do not change any other parts of the code
    print(encoded_X[0,:])
    return encoded_y, encoded_X

main()

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]


(array([1, 0, 0, ..., 0, 1, 0]),
 array([[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 1., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.]]))